[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.0.1"
itermore = "0.4.0"
glfw = "0.45.0"
serde_json = "1.0.89"
serde = "1.0.150"
rayon = "1.5.3"
indicatif = { version = "0.17.2", features = ["rayon"] }
ring = "0.17.0-alpha.11"